stages:
  ingest:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
  preprocess:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/processed
